/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import {
  PAGINATION_SCHEMA,
  createPaginationResponseSchema,
  WorkflowSchema,
  CreateWorkflowSchema,
} from "@repo/contracts";

export const appRouter = t.router({
  user: t.router({
    getUser: publicProcedure.query(
      async () => "PLACEHOLDER_DO_NOT_REMOVE" as any,
    ),
  }),
  workflow: t.router({
    getWorkflows: publicProcedure
      .input(PAGINATION_SCHEMA)
      .output(createPaginationResponseSchema(WorkflowSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    createWorkflow: publicProcedure
      .input(CreateWorkflowSchema)
      .output(CreateWorkflowSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getWorkflowById: publicProcedure
      .input(
        z.object({
          id: z.string(),
        }),
      )
      .output(CreateWorkflowSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    removeWorkflow: publicProcedure
      .input(
        z.object({
          id: z.string(),
        }),
      )
      .output(WorkflowSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
  }),
});

export type AppRouter = typeof appRouter;
