/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { createWorkflowSchema } from "/home/riyad/Documents/N8N-MONOREPO/apps/api/src/workflow/./dtos/create-workflow.schema";

const appRouter = t.router({
  user: t.router({
    getUser: publicProcedure.query(
      async () => "PLACEHOLDER_DO_NOT_REMOVE" as any,
    ),
  }),
  workflow: t.router({
    getWorkflows: publicProcedure
      .output(z.array(createWorkflowSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    createWorkflow: publicProcedure
      .input(createWorkflowSchema)
      .output(createWorkflowSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
  }),
});

export type AppRouter = typeof appRouter;
